Add a DCC subsystem for handling the SEND/ACCEPT commands
glguy/irc-core pull request #64
Opened 2019-02-17 02:10 UTC by RubenAstudillo

This series of patches add at user level the following commands:
````
    /dcc          : List the DCC SEND requests
    /dcc accept n : Start downloading the n request
    /dcc resume n : Start downloading the n request appending the file on the download-dir
    /dcc cancel n  : Cancel the n download
````
I've tested their implementation for a couple of weeks on a couple of fileservers. They satisfy the DCC SEND/RESUME/ACCEPT protocol for what it does a practice. What will be improved on further patches can be UI related matter for `/dcc` and see how to rate-limit the transfer so they don't consume all the bandwidth available.

The series of patches can be squash if desired.

2019-02-17 04:38 UTC, glguy requested changes
I think you've done a nice job of matching the style and structure of the client with this change. I'd got some things annotated below that we should look at.

2019-02-17 04:38 UTC, glguy commented on src/Client/Configuration.hs
> +                 _configDownloadDir = maybe home id maybeDownloadDir
`fromMaybe`

2019-02-17 04:38 UTC, glguy commented on src/Client/Configuration.hs
> +     home <- getEnv "HOME" -- guarranted by POSIX?
Let's use [getHomeDirectory](http://hackage.haskell.org/package/directory-1.3.3.2/docs/System-Directory.html#v:getHomeDirectory)

2019-02-17 04:38 UTC, glguy commented on src/Client/Configuration.hs
> +                               "Path to the directory where to place DCC downloads"
`"Path to DCC download directory. Defaults to home directory."`

2019-02-17 04:38 UTC, glguy commented on src/Client/EventLoop.hs
> +                    maybe (return ())
Instead of `maybe (return ())`: [traverse_](http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Foldable.html#v:traverse_)

2019-02-17 04:38 UTC, glguy commented on src/Client/State/Focus.hs
> +  | FocusDCC
It's obvious, but could you put a haddock command on this constructor?

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +  | Pending | NotExist
Is it necessary to have `NotExist`? Could we use `Maybe ConnectionStatus` for cases where nonexistence is possible? This would save an impossible case in the View module.

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +                    -- Compatibility hack
glirc doesn't need compatibility, let's just bump the lower-bound on async and knock out hacks

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +              { cpFamily = AF_INET, cpHost = from
Do we have to back IPv4 in here? What would it take to work on both 4 and 6?

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +          && userFrom == (_dccFromInfo offer)
Extra parentheses not needed

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +
I'd rather just see do-notation than a nested applicative expression

```haskell
sendFormat network userFrom =
  do name      <- string "SEND" *> space *> nameFormat
     addr      <- ipv4Dotted <$ space <*> decimal
     port      <- space *> decimal
     totalsize <- space *> decimal
     return (DCCOffer network userFrom addr port (Text.unpack name) totalsize 0)
```

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +      target = Text.unpack $ views uiNick idText (_dccFromInfo offer)
`views (uiNick . dccFromInfo) (Text.unpack . idText) offer`

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +    Nothing -> error "Not a valid key"
Could this kill the client if something went wrong? Could we silently ignore a missing key instead? What would the consequences be?

2019-02-17 04:38 UTC, glguy commented on src/Client/State/DCC.hs
> +  let transfer = maybe (error "Wrong index") id $ view (dsTransfers . at key) dccstate
What are the consequences of `error` here? When can this happen? Can we handle this more gracefully or silently?

2019-02-17 04:38 UTC, glguy commented on src/Client/Commands.hs
> +    $ ClientCommand cmdDcc noClientTab
Future work: smarter tab completion for the commands (accept, resume, cancel) and for the active DCC IDs. Not necessary for this PR however.

2019-02-17 04:42 UTC, glguy commented on src/Client/State/DCC.hs
> +  } deriving (Show, Eq)
Let's make the fields strict where it makes sense, basically everything but the fields represented by a `[]`

2019-02-17 04:43 UTC, glguy commented on src/Client/State/DCC.hs
> +  (DCCState off1 tran1) <> (DCCState off2 tran2) =
We don't need parentheses around these patterns

2019-02-17 04:43 UTC, glguy commented on src/Client/State/DCC.hs
> +instance Semigroup DCCState where
I'd prefer just not having this instance. I find reusing `Monoid` and `Semigroup` for things like this to be a hack. If we keep it, let's put a haddock command explaining the behavior.

2019-02-17 04:44 UTC, glguy commented on src/Client/State/DCC.hs
> +  , _dtStatus   :: ConnectionStatus
Strict fields when it makes sense.

2019-02-17 04:45 UTC, glguy commented on src/Client/State/DCC.hs
> +  deriving (Show, Eq)            -- Word32 is the offset
Strict fields, small fields like these will unpack automatically and we don't benefit from any extra laziness here.

2019-02-17 04:48 UTC, glguy commented on src/Client/State/DCC.hs
> +         recvChan2 <- atomically $ dupTChan recvChan1
Could you help me understand why we had to duplicate the channel? I just don't quite understand the thread model here.

2019-02-17 04:50 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +    Nothing -> error "Not a valid key"
We could simply ignore it. This function came to be as some code that was too big to be included directly on `doDCCUpdate`, so the checking that that `case` was not `Nothing` it's done there (and it's the only place where `acceptUpdate` is called. I put an `error` so playing on ghci would show that something was obviously wrong, but I will change that to "do nothing".

2019-02-17 04:51 UTC, RubenAstudillo commented on src/Client/Commands.hs
> +    $ ClientCommand cmdDcc noClientTab
Right! it would be nice!

2019-02-17 04:53 UTC, glguy commented on src/Client/State/DCC.hs
> +percent a total = fromIntegral $
`percent a total = fromIntegral (fromIntegral a * 100 `div` fromIntegral total :: Word64) -- avoid overflow`

2019-02-17 04:53 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +instance Semigroup DCCState where
Yeah, I onlye provide `Semigroup` for `Monoid`. I wanted to use `empty` as a default value for `ClientState`. I will provide just a constant as alternative.

2019-02-17 05:03 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +         recvChan2 <- atomically $ dupTChan recvChan1
OK, so `recvChan1` is what `sendStream` uses for acknowledgement of the `recv`, this sends how many bytes have we recieved from that `socket` so far. DCC SEND/ACCEPT as a protocol says that after each `recv` you have to `send` thit acknowledgement. In practice the server doesn't care about the acknowledgement, it will keep sending and not let you `send` stuff until the transfer finishes (which is why we start an extra thread to be blocked on these `send` request). I've checked this behavior with wireshark on at least two machines and with different fileservers on rizon, it fails if you do what the bare protocol describes.

But we also want to report how much progress have we done on a download, but maintaining the blocking behavior of `sendStream` has respect `recvChan1`. The solution is `dupTChan recvChan1` onto `recvChan2`, so `report` blocks on the latter generating `DCCUpdate` event that the `eventLoop` process and lets `sendStream` have the blocking behavior respect to `recvChan1`.

2019-02-17 05:10 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +                    -- Compatibility hack
I was gonna ask this! Got it.

2019-02-17 05:16 UTC, RubenAstudillo commented on src/Client/State/Focus.hs
> +  | FocusDCC
I forgot!

2019-02-17 05:29 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +
I'll also change `acceptFormat`.

2019-02-17 05:36 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +  let transfer = maybe (error "Wrong index") id $ view (dsTransfers . at key) dccstate
The `key` is guaranteed to be valid as is generated by the thread at that key and we don't remove any item of `DCCState`. But I didn't know how to convince the compiler that prism branch was the valid one. I'll just match on the `Just` value returned.

2019-02-17 05:58 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +  | Pending | NotExist
`NotExist` is neccesary for the case `cmdDcc` is called with an invalid key. It's never stored on the `ConnectionStatus` of a `DCCTransfer`, that is why it is impossible to be shown on the View module. That also why a `Maybe ConnectionStatus` won't work as when we set that field, it is never `NotExist`.

See also the `statusAtKey` function, that is the only one capable of returning a `NotExist`.

2019-02-17 05:58 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +  (DCCState off1 tran1) <> (DCCState off2 tran2) =
Removing all together

2019-02-17 06:02 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +              { cpFamily = AF_INET, cpHost = from
Protocol stuff. The DCC that uses IPv6 is implementation specific. I found a fileserver that uses IPv6 and I am asking for the fileserver code plus checking what hexchat does with IPv6. I will do some tests and send a patch after that.

2019-02-17 06:08 UTC, RubenAstudillo commented on src/Client/State/DCC.hs
> +  let transfer = maybe (error "Wrong index") id $ view (dsTransfers . at key) dccstate
There is a single call to `reportStopWithStatus` and it guaranteed to be called on a valid `key`. I will just match on the `Just` returned by the `prism`.

2019-02-17 15:58 UTC, glguy approved these changes

2019-02-17 16:18 UTC, glguy commented
I tried out the transfer and had some issues and questions:

1. When I ran /dcc with no active transfers the window was empty. I've been showing a message for empty lists. Try `/masks q` on a channel with no quiet modes.
2. My first transfer ended with: Socket failure 74% (transfer from Textual). I don't know what went wrong, but the file only partially transferred. Which clients have you tried with?
3. Incoming DCC offers not rendered in client, we should add a new message type similar to CtcpAction so that the user won't have to use the detail view to learn about DCC offers
4. How do I remove failed transfers from /dcc? After my transfer above I couldn't figure out how to remove the transfer from the list.
5. DCC filenames are not sanitized; they could overwrite existing files, and they could contain directory separators

2019-02-17 17:11 UTC, glguy requested changes
I tried out the transfer and had some issues and questions:

1. When I ran /dcc with no active transfers the window was empty. I've been showing a message for empty lists. Try `/masks q` on a channel with no quiet modes.
2. My first transfer ended with: Socket failure 74% (transfer from Textual). I don't know what went wrong, but the file only partially transferred. Which clients have you tried with?
3. Incoming DCC offers not rendered in client, we should add a new message type similar to CtcpAction so that the user won't have to use the detail view to learn about DCC offers
4. How do I remove failed transfers from /dcc? After my transfer above I couldn't figure out how to remove the transfer from the list.
5. DCC filenames are not sanitized; they could overwrite existing files, and they could contain directory separators

2019-02-19 13:55 UTC, RubenAstudillo commented
I'll answer on order

1. I added a basic countdown based on the code for `MaskList.hs` that shows at the bottom the total and how many transfers are running.

2. That's odd, at least initiating a transfer from hexchat to this branch of code works as expected. Also file-servers on Rizon work too. I've had problems trying to run `Textual`. We could try to do a transfer from your end to my client and see what I log.

3. Yes, pressing F2 to see if something has come will get old. I wanna read the source code a little more to see how the /view-* functionality is implemented.

4. Currently you can't remove anything from the list. There is nothing fundamental stopping it, I just didn't want to complicate the options under "/dcc" with an hypothetical "/dcc remove".  I am thinking on possible directions on how to present all the functionality to the user and not being overbearing. 

5. Now they are. At parse time we use `takeFileName` to clear path separators and at "/dcc (resume|accept)" we check if the file is a directory on the download-dir. We assume that if the user says "resume" we want to append to whatever file is on the download-dir with the same name and if he says "accept" he wants to overwrite.

2019-02-24 19:38 UTC, RubenAstudillo commented
I added a "/dcc clear" command that removes transfers from the "/dcc" list (if they are allowed to be removed).

2019-02-26 03:37 UTC, RubenAstudillo commented
Now it signals as a `WindowLine` when a "DCC SEND" command is received (so the user checks the "/dcc" list). It looks like this

![gato](https://user-images.githubusercontent.com/1875145/53385737-3aef9680-395e-11e9-8c41-bd323f1d1296.png)
The previous sequence shows only the "DCC SEND", even if send a "DCC RESUME" and it's followed by a "DCC ACCEPT" those are not showed, as it's just an implementation detail on how resume is done on DCC.

![screenshot_20190226_003157](https://user-images.githubusercontent.com/1875145/53385775-62466380-395e-11e9-9559-d9c660a3a959.png)
This is corresponding view on "/dcc".

With this, I consider the pull request is completed :-)

2019-03-14 03:23 UTC, merged